# Generated by Django 4.2.7 on 2024-06-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='myfile')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
