# Generated by Django 4.2.7 on 2024-06-11 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adresse',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=200, verbose_name='Name'),
        ),
    ]
